
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 17;
  public static final int OVER = 18;
  public static final int LT = 11;
  public static final int ELSE = 3;
  public static final int PLUS = 15;
  public static final int RBRACE = 26;
  public static final int RPAREN = 22;
  public static final int INT = 5;
  public static final int LTE = 12;
  public static final int SEMI = 19;
  public static final int WHILE = 4;
  public static final int RETURN = 6;
  public static final int ERROR = 29;
  public static final int IF = 2;
  public static final int LBRACE = 25;
  public static final int LBRACKET = 23;
  public static final int LPAREN = 21;
  public static final int GT = 13;
  public static final int ID = 27;
  public static final int GTE = 14;
  public static final int RBRACKET = 24;
  public static final int NUM = 28;
  public static final int COMMA = 20;
  public static final int EOF = 0;
  public static final int MINUS = 16;
  public static final int error = 1;
  public static final int ASSIGN = 8;
  public static final int EQ = 9;
  public static final int NEQ = 10;
  public static final int VOID = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "INT",
  "RETURN",
  "VOID",
  "ASSIGN",
  "EQ",
  "NEQ",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "ID",
  "NUM",
  "ERROR"
  };
}

